name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install xmllint
      run: sudo apt-get install libcunit1-dev
    - name: Bootstrap
      run: ./bootstrap.sh
    - name: configure
      run: ./configure --enable-gcov
    - name: make check
      run: make check

